# Generated by Django 5.2.11 on 2026-02-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_report', models.FileField(upload_to='reports/')),
                ('new_report', models.FileField(upload_to='reports/')),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
